src/Rbins/PersoBundle/Entity/Catalogue.php
<?php

namespace Rbins\PersoBundle\Entity;

use Rbins\PersoBundle\Utils\Util as Util;

/**
 * Rbins\PersoBundle\Entity\Catalogue
 */
class Catalogue
{
    /**
     * @var integer $id
     */
    private $id;

    /**
     * @var string $type
     */
    private $type;

    /**
     * @var string $code
     */
    private $code;

    /**
     * @var booolean $is_active
     */
    private $is_active;

    /**
     * @var string $ehr_code
     */
    private $ehr_code;

    /**
     * @var string $name_fr
     */
    private $name_fr;

    /**
     * @var string $name_nl
     */
    private $name_nl;

    public function __toString()
    {
      return $this->getNameEn();
    }

    public function getLabel($locale) {
      $fct = 'getName'.$locale;
      return $this->$fct();
    }
    public function getNameEn()
    {
      return $this->getNameFr() .'-'.$this->getNameNl() ;
    }

    public function getCatalogueNameEn() {
      if(!$this->getIsActive()) return '$$'.$this->getNameEn();
      return $this->getNameEn();
    }
    public function getCatalogueNameFr() {
      if(!$this->getIsActive()) return '$$'.$this->getNameFr();
      return $this->getNameFr();
    }
    public function getCatalogueNameNl() {
      if(!$this->getIsActive()) return '$$'.$this->getNameNl();
      return $this->getNameNl();
    }

    public function getFilter()
    {
      return  Util::unaccent(strtolower($this->getNameFr() .' '.$this->getNameNl()));
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set is_active
     *
     * @param boolean $isActive
     * @return Catalogue
     */
    public function setIsActive($isActive)
    {
        $this->is_active = $isActive;

        return $this;
    }

    /**
     * Get is_active
     *
     * @return boolean
     */
    public function getIsActive()
    {
        return $this->is_active;
    }
    /**
     * @var string
     */
}

src/Rbins/PersoBundle/Controller/CatalogueController.php
<?php

namespace Rbins\PersoBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;


class CatalogueController extends Controller {

  public function listAction($catalogue) {
    $this->checkCatalogue($catalogue);
    if( in_array($catalogue, array('City', 'MedCenter', 'Department', 'Building'))) {
      $repo = $this->getDoctrine()->getRepository('RbinsPersoBundle:'.$catalogue);
    }else {
      $repo = $this->getDoctrine()->getRepository('RbinsPersoBundle:Catalogue');
    }
    $entities = $repo->findAllCatalogueOrdered($catalogue);
    return $this->render('RbinsPersoBundle:Catalogue:list.html.twig',
      array('items' => $entities, 'catalogue'=> $catalogue));
  }

  public function loadItemAction($catalogue, $id, Request $request){
    if($id == '-1') {
      $entity = $this->createEmptyEntity($catalogue);
    }
    else {
      $entity = $this->getItem($catalogue, $id);
    }
    $form = $this->createForm($this->createEmptyForm($catalogue, $request), $entity);

    return $this->render('RbinsPersoBundle:Catalogue:catalogue_form.html.twig',
      array('form' => $form->createView(), 'catalogue' => $catalogue));
  }

  public function editItemAction($catalogue, Request $request){
    if($request->query->get('id') === '') {
      //new
      $entity = $this->createEmptyEntity($catalogue);
    }
    else {
      $entity = $this->getItem($catalogue, $request->query->get('id'));
    }
    $form = $this->createForm($this->createEmptyForm($catalogue, $request), $entity);
    $form->submit($request);
    if ($form->isValid()) {
      $em = $this->getDoctrine()->getManager();
      $em->persist($entity);
      $em->flush();
      return $this->render('RbinsPersoBundle:Catalogue:single_catalogue.html.twig', array('item' => $entity,'catalogue' => $catalogue));
    } else {
      $this->get('logger')->
        err('An error occurred while submiting catalogue: '. ( (string) $form->getErrors(true, false) ));
      return $this->render('RbinsPersoBundle:Catalogue:catalogue_form.html.twig',
        array('form' => $form->createView(), 'catalogue' => $catalogue));
    }
  }


  public function deleteItemAction($catalogue, $id) {
    $entity = $this->getItem($catalogue, $id);

    $em = $this->getDoctrine()->getManager();
    try {
      $em->remove($entity);
      $em->flush();
    } catch(\Exception $e) {
      $this->get('logger')->info('Remove still ref : '.$catalogue);
      return new Response(json_encode(array('status'=>'error', 'msg' => $e->getMessage()))) ;
    }
    return new Response(json_encode(array('status'=>'ok'))) ;
  }

  public function toggleItemAction($catalogue, $id, $status) {
    $is_active = ($status == 'false' ? false : true);

    $entity = $this->getItem($catalogue, $id);
    $entity->setIsActive($is_active);
    $em = $this->getDoctrine()->getManager();
    $em->persist($entity);
    $em->flush();
    return new Response(json_encode(array('status'=>'ok','data'=> ($is_active ? 'true':'false')))) ;
  }


  public function loadListAction($catalogue, $letter){
    $this->checkCatalogue($catalogue);
    $repo = $this->getDoctrine()->getRepository('RbinsPersoBundle:City');
    $entities = $repo->findAllStartingWith($catalogue, $letter);

    return $this->render('RbinsPersoBundle:Catalogue:items_list.html.twig',
      array('items' => $entities, 'catalogue' => $catalogue));
  }


  protected function getItem($catalogue, $id) {
    $this->checkCatalogue($catalogue);
    return $this->getDoctrine()
      ->getRepository('RbinsPersoBundle:'.$catalogue)
      ->find($id);
  }

  protected function checkCatalogue($catalogue) {
      if( ! in_array($catalogue, array('Grade', 'Cause', 'Status', 'Reason', 'FunctFamily', 'CataloguePremium',
      'SalaryGrade', 'MaritalStatus', 'ContractDuration', 'ExitReason','SubLevel','Country','ContractComment',
      'City', 'MedCenter', 'Department', 'DocType', 'Degree','Frame','WorkFunction'))) {

        throw $this->createNotFoundException('The Catalogue does not exist');
      }
  }

  protected function createEmptyEntity($catalogue) {
    $this->checkCatalogue($catalogue);
    $e_str= "Rbins\PersoBundle\Entity\\".$catalogue;
    return $entity = new $e_str;
  }

  protected function createEmptyForm($catalogue, Request $request) {
    $this->checkCatalogue($catalogue);
    $e_str= "Rbins\PersoBundle\Form\\".$catalogue."Type";
    return $entity = new $e_str($request->getLocale());
  }
}

src/Rbins/PersoBundle/Resources/views/Catalogue/catalogue_form.html.twig
<div class="well">
  <form id="inline_form" class="form-inline" data-id="{{form.vars.value.id}}">
    {{ form_errors(form) }}

    {% if catalogue == 'City' %}

      <div class="row">
        {{ form_row(form.code, { rowclass: 'span3' }) }}
      </div>
      <div class="row">
        {{ form_row(form.name, { rowclass: 'span6' }) }}
        {{ form_row(form.Country,  { rowclass: 'span6' }) }}
      </div>

    {% elseif catalogue == 'MedCenter' %}

      <div class="row">
        {{ form_row(form.name) }}
        {{ form_row(form.address) }}
        {{ form_row(form.City) }}
      </div>
      <div class="row">
        {{ form_row(form.phone) }}
        {{ form_row(form.fax) }}
      </div>

    {% elseif catalogue == 'Department' %}

      <div class="row">
          {{ form_row(form.code, { rowclass: 'span6' }) }}
      </div>

      <div class="row">
          {{ form_row(form.name_fr, { rowclass: 'span6' }) }}
          {{ form_row(form.name_nl, { rowclass: 'span6' }) }}
      </div>
      <div class="row">
          {{ form_row(form.name_en, { rowclass: 'span6' }) }}
          {{ form_row(form.level, { rowclass: 'span6' }) }}
      </div>
      <div class="row">
          {{ form_row(form.is_active, { rowclass: 'span6' }) }}
          {{ form_row(form.Parent, { rowclass: 'span6' }) }}
      </div>

    {%else%}{#Other catalogues #}
    {% if form.ehr_code is defined %}
      <div class="row">
        {{ form_row(form.is_active, { rowclass: 'span2' }) }}
      </div>
      <div class="row">
        {{ form_row(form.code, { rowclass: 'span6' }) }}
        {{ form_row(form.ehr_code, { rowclass: 'span6' }) }}
      </div>
    {% elseif form.code is defined %}    
      <div class="row">
        {{ form_row(form.is_active, { rowclass: 'span2' }) }}
        {{ form_row(form.code, { rowclass: 'span5' }) }}
      </div>
    {% else %}    
      <div class="row">
        {{ form_row(form.is_active, { rowclass: 'span2' }) }}        
      </div>    
    {%endif%}
    {% if form.level is defined %}
      <div class="row">
        {{ form_row(form.level, { rowclass: 'span2', 'attr': {'class':'input-small'} }) }}
      </div>
    {% endif %}
      <div class="row">
        {{ form_row(form.name_fr, { rowclass: 'span6', 'attr': {'class':'input-xxlarge'} }) }}
      </div>
      <div class="row">
        {{ form_row(form.name_nl, { rowclass: 'span6', 'attr': {'class':'input-xxlarge'} }) }}
      </div>
    {%endif%}

    {{ form_rest(form) }}

    <div class="row">
      <button type="reset" class="form_cancel btn">{% trans %}perso.form.cancel{% endtrans%}</button>
      <input type="submit" class="btn btn-primary btn-large" value="{% trans %}perso.form.submit{% endtrans%}"  />
    </div>

  </form>
</div>

src/Rbins/PersoBundle/Resources/views/Catalogue/items_list.html.twig
{% for item in items %}
  {% include 'RbinsPersoBundle:Catalogue:single_catalogue.html.twig' with {'item': item,'catalogue': catalogue} %}
{% endfor %}

src/Rbins/PersoBundle/Resources/views/Catalogue/list.html.twig
{% extends 'RbinsPersoBundle::layout.html.twig' %}

{% block sidebar%}
  
{% endblock%}

{% block content %}
{% set title %}perso.catalogue.{{catalogue}}.title{%endset%}
{% set desc %}perso.catalogue.{{catalogue}}.description{%endset%}

<h1>{{ title|trans }}</h1>
<p>{{ desc|trans }}</p>


{% if catalogue == 'City' %}
<ul class="filter_letter">
{% for letter in 'a'|upper..'z'|upper %}
  <li>{{letter}}</li>
{% endfor %}
</ul>
{% endif %}

<div class="filter_search">
  <p class="input-append">
    <input type="text" autocomplete="off" placeholder="{% trans %}perso.catalogue.filter{% endtrans %}"
      class="input-xlarge" id="search_input"><span class="add-on"><i class="icon-filter"></i></span>
  </p>
</div>


<ul class="catalogue_list">
{% if catalogue != 'City' %}
  {% include 'RbinsPersoBundle:Catalogue:items_list.html.twig' with {'items': items,'catalogue': catalogue} %}
{%else%}
  <li><div class="alert alert-info">{% trans %}perso.catalogue.City.choose_letter{% endtrans %}</div></li>
{% endif %}
</ul>

{% if is_granted('ROLE_HR_ADMIN') %}
  <button class="btn btn-success add">{% trans %}perso.form.add{% endtrans %}
    <i class="icon-plus-sign icon-white"></i>
  </button>
{% endif %}

<script type="text/javascript">
var catalogue = '{{catalogue}}';
delete_success_msg = '{% trans %}perso.catalogue.delete.success{% endtrans %}';
delete_error_msg = '{% trans %}perso.catalogue.delete.error{% endtrans %}';
save_success_msg = '{% trans %}perso.catalogue.save.success{% endtrans %}';


$(document).ready(function(){
    $('.catalogue_list > li .edit ').click(initInEdit);
    $('.catalogue_list > li .delete ').click(inDelete);
    $('.catalogue_list > li .toggle_active ').click(inToggleActive);
    $('.add ').click(inAdd);
    $('#search_input').bind('keyup', fitler_catalogue);
    $('.filter_letter li').click(loadLetter);
});
</script>
{% endblock %}

src/Rbins/PersoBundle/Resources/views/Catalogue/single_catalogue.html.twig
{% if catalogue == 'City' %}
  <li data-id="{{item.id}}" data-filter="{{item.filter|e}}">
    <div class="row">
      <span class="catalogue_code span2" title="{%trans%}perso.catalogue.label.code{%endtrans%}">{{item.code}}</span>
      <span class="span4" title="{%trans%}perso.catalogue.label.name{%endtrans%}">{{item.name}}</span>
      <span class="span4" title="{%trans%}perso.catalogue.label.country{%endtrans%}">{{item.Country}}</span>
      <div class="actions span1">
        {% if is_granted('ROLE_HR_ADMIN') %}
          <i class="icon-pencil edit" title="{{ 'perso.form.edit' |trans|e }}"></i>
          <i class="icon-remove-circle delete" data-msg="{{ 'perso.form.delete' |trans|e }}"></i>
        {% endif %}
      </div>
    </div>
  </li>
{% elseif catalogue == 'Department' %}
  <li data-id="{{item.id}}" data-filter="{{item.filter|e}}" class="{% if not item.isActive %}catalogue_inactive{% endif %}" >
    <div class="row">
      {% set lvl %}perso.entity.department.level.{{item.level}}{%endset%}
      <span class="span2 {% if item.level == 'section' %}dpt_space{% endif %}">{{lvl| trans }}</span>
      <span class="span1" title="{%trans%}perso.catalogue.label.code{%endtrans%}">{{ item.code }}</span>
      <span class="span2" title="{%trans%}perso.catalogue.label.name_fr{%endtrans%}">{{item.nameFr}}</span>
      <span class="span2" title="{%trans%}perso.catalogue.label.name_nl{%endtrans%}">{{item.nameNl}}</span>
      <span class="span2" title="{%trans%}perso.catalogue.label.name_en{%endtrans%}">{{item.nameEn}}</span>
      <span class="span2" title="{%trans%}perso.catalogue.label.parent{%endtrans%}">{{item.Parent}}</span>
      <div class="actions span1">
        {% if is_granted('ROLE_HR_ADMIN') %}
          <i class="icon-pencil edit" title="{{ 'perso.form.edit' |trans|e }}"></i>
          <i class="icon-ban-circle toggle_active" title="{{ 'perso.form.toggle' |trans|e }}"></i>
          <i class="icon-remove-circle delete" title="{{ 'perso.form.delete' |trans|e }}" data-msg="{{ 'perso.form.delete_msg' |trans|e }}"></i>
        {% endif %}
      </div>
    </div>
  </li>
{% elseif catalogue == 'MedCenter' %}
  <li data-id="{{item.id}}" data-filter="{{item.filter|e}}">
    <div class="row">
      <span class="span2" title="{%trans%}perso.catalogue.label.name{%endtrans%}">{{item.name}}</span>
      <span class="span2" title="{%trans%}perso.catalogue.label.adress{%endtrans%}">{{item.address}}</span>
      <span class="span2" title="{%trans%}perso.catalogue.label.city{%endtrans%}">{{item.City.name}}</span>
      <span class="span2" title="{%trans%}perso.catalogue.label.phone{%endtrans%}">{{item.phone}}</span>
      <span class="span2" title="{%trans%}perso.catalogue.label.fax{%endtrans%}">{{item.fax}}</span>
      <div class="actions span1">
        {% if is_granted('ROLE_HR_ADMIN') %}
          <i class="icon-pencil edit" title="{{ 'perso.form.edit' |trans|e }}"></i>
          <i class="icon-remove-circle delete" title="{{ 'perso.form.delete' |trans|e }}" data-msg="{{ 'perso.form.delete_msg' |trans|e }}"></i>
        {% endif %}
      </div>
    </div>
  </li>

{%else%}
  <li data-id="{{item.id}}" class="{% if not item.isActive %}catalogue_inactive{% endif %}" 
      data-filter="{{item.filter|e}}">
    <div class="row">
      {% if item.level is defined %}
        <span class="span1" title="{%trans%}perso.catalogue.label.level{%endtrans%}">{{item.level?item.level: '-' }}</span>
      {% endif %}
      {% if item.ehrCode is defined %}
        <span class="span1" title="{%trans%}perso.catalogue.label.ehr_code{%endtrans%}">{{item.ehrCode ? item.ehrCode: '-'}}</span>
      {% endif %}
      {% if item.code is defined %}
	<span class="catalogue_code span1" title="{%trans%}perso.catalogue.label.code{%endtrans%}">{{item.code}}</span>
      {% endif %}
      <span class="span4" title="{%trans%}perso.catalogue.label.name_fr{%endtrans%}">{{item.nameFr}}</span>
      <span class="span4" title="{%trans%}perso.catalogue.label.name_nl{%endtrans%}">{{item.nameNl}}</span>
      <div class="actions span1">
        {% if is_granted('ROLE_HR_ADMIN') %}
          <i class="icon-pencil edit" title="{{ 'perso.form.edit' |trans|e }}"></i>
          <i class="icon-ban-circle toggle_active" title="{{ 'perso.form.toggle' |trans|e }}"></i>
          <i class="icon-remove-circle delete" title="{{ 'perso.form.delete' |trans|e }}" data-msg="{{ 'perso.form.delete_msg' |trans|e }}"></i>
        {% endif%}
      </div>
    </div>
  </li>
{%endif%}